# Site settings
title: Learning to Learn (Web Development)
header-img: img/home-bg.png
email: joannachristinewheeler@gmail.com
copyright_name: joannawheeler
description: > # this means to ignore newlines until "baseurl:"
  Me and Learn.co
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: takeawoogiewithyou
github_username:  joannawheeler
learn_profile: joannawheeler
email_username: joannachristinewheeler@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
